[package]
name = "contracts"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "21.0.0"
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
soroban-sdk = { version = "21.0.0", features = ["testutils"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1

[profile.release-with-logs]
inherits = "release"
debug-assertions = true

[features]
testutils = ["soroban-sdk/testutils"]
default = ["wee_alloc"]